import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/runtime.ts",
    "src/types.ts",
    "src/conversation-manager.ts",
    "src/conversation-agent-turn-admission.ts",
    "src/conversation-control.ts",
    "src/run-turn.ts",
    "src/ephemeral-run-buffer.ts",
    "src/confirmation-hub.ts",
    "src/control-admission.ts",
    "src/conversation-assignment.ts",
    "src/job-assignment.ts",
    "src/delivery.ts",
    "src/resource-governor.ts",
    "src/scheduler-authority.ts",
    "src/scheduler-global-state.ts",
    "src/conversation-assignment-authority.ts",
    "src/job-assignment-authority.ts",
    "src/scheduler-job-commit.ts",
    "src/scheduler-conversation-publisher.ts",
    "src/scheduler-user-notices.ts",
    "src/global-mutation-commit-coordinator.ts",
    "src/global-mutation-participant.ts",
    "src/deferred-global-intent-review.ts",
    "src/deferred-global-intents.ts",
    "src/channel-challenge-outbox.ts",
    "src/conversation-transfer.ts",
    "src/session-state-adapter.ts",
    "src/publish-result-product-language.ts",
    "src/test-support/s7-durable.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "node24",
});
