export {
  type ChannelAdapter,
  type ChannelBindingPolicy,
  type ChannelCapabilities,
  type ChannelChallengeAction,
  type ChannelChallengeMessage,
  type ChannelConfig,
  type ChannelContext,
  type ChannelEventMap,
  type ChannelLogger,
  type ChannelState,
  type ChannelStatus,
  type ChatType,
  type DeliveryResult,
  type DeliveryTarget,
  type DeliveryTargetDto,
  type Disposable,
  type HttpHandler,
  type InboundMessage,
  type OutboundContent,
  type OutboundContentDto,
  DEFAULT_BINDING_POLICY,
} from "./types.js";

export {
  type ApprovableChannel,
  type ApprovalHandle,
  type EditableChannel,
  type ReactableChannel,
  type StreamableChannel,
  type StreamHandle,
  type ThreadableChannel,
  type TypingChannel,
  type ChallengeChannel,
  isApprovable,
  isEditable,
  isReactable,
  isStreamable,
  isThreadable,
  isTyping,
  isChallengeChannel,
} from "./capabilities.js";

export { ChannelRegistry, type ChannelRegistryOptions } from "./registry.js";
