import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { MAIN_IDENTITY_INSTRUCTIONS, mainProfile, subAgentProfile } from "@zhixing/orchestrator/profile";
import { buildSystemPrompt, CACHE_BOUNDARY, SUB_AGENT_SEGMENTS } from "@zhixing/orchestrator/runtime";
import type { ToolDefinition } from "@zhixing/core/types";
import { powerProfile, WORKING_MODE_TEXT } from "../workscene-agent-guidance.js";
import { createWorkmodeEnterTool, createWorkmodeExitTool } from "../workmode-tools.js";
import { selectJobRuntimeTools } from "../job-runtime-tool-selection.js";

type WorksceneProfileInput = Parameters<typeof powerProfile>[0];

function makeScene(overrides: Partial<WorksceneProfileInput> = {}): WorksceneProfileInput {
  return {
    id: "scene-x",
    name: "知行 CLI 开发",
    hasSceneControlTools: true,
    ...overrides,
  };
}

describe("powerProfile(scene)", () => {
  it("retains isolated explicit identity inputs", () => {
    const first = powerProfile(makeScene(), { agentIdentity: { displayName: "First" } });
    const second = powerProfile(makeScene(), { agentIdentity: { displayName: "Second" } });
    expect(first.name).toBe("First");
    expect(second.name).toBe("Second");
    expect(mainProfile().name).toBe("知行");
    expect(powerProfile(makeScene()).name).toBe("知行");
    expect(first.name).toBe("First");
  });
  it("有已解析 workspace → 主工具全集（含文件工具）", () => {
    const p = powerProfile({ ...makeScene(), hasWorkspace: true });
    expect(p.enabledTools).toEqual([
      "read",
      "write",
      "edit",
      "glob",
      "grep",
      "bash",
      "web_fetch",
      "load_skill",
      "save_skill",
      "admit_skill",
      "Task",
    ]);
  });

  it("无 workspace → 剔除全部本地文件类工具（by-construction 隔离）", () => {
    const p = powerProfile({ ...makeScene(), hasWorkspace: false });
    // load_skill / save_skill 读写 app-state(~/.zhixing/skills)、非 workdir
    // 本地文件,故保留。
    expect(p.enabledTools).toEqual([
      "web_fetch",
      "load_skill",
      "save_skill",
      "Task",
    ]);
    for (const fileTool of ["read", "write", "edit", "glob", "grep", "bash"]) {
      expect(p.enabledTools).not.toContain(fileTool);
    }
  });

  it("instructions 含基础身份、场景内属性管理与退出自判；capabilities 同 main", () => {
    const p = powerProfile(makeScene({ name: "写作场景" }));
    expect(p.instructions).toContain(MAIN_IDENTITY_INSTRUCTIONS);
    expect(p.instructions).toContain("写作场景");
    expect(p.instructions).toContain("rename this scene");
    expect(p.instructions).toContain("change its device workspace");
    expect(p.instructions).toContain("clear its workspace binding");
    expect(p.instructions).not.toContain("memory");
    // 退出自判：显式指向 workmode_exit 工具，而非仅"叙述完成"
    expect(p.instructions).toContain("workmode_exit");
    expect(p.capabilities).toEqual({
      canSpawnSubAgents: true,
      userFacing: true,
    });
    expect(p.role).toBe("main");
  });

  it("同一 scene 多次调用 instructions byte-equal（静态前缀缓存可复用）", () => {
    const scene = { ...makeScene(), hasWorkspace: true };
    expect(powerProfile(scene).instructions).toBe(
      powerProfile(scene).instructions,
    );
  });
});

function stubTool(name: string): ToolDefinition {
  return { name, description: `stub ${name}`, inputSchema: { type: "object" }, call: async () => ({ content: "" }) };
}

describe("Workscene model guidance", () => {
  const entry = () => createWorkmodeEnterTool({ get: async () => null });
  const hash = (text: string) => createHash("sha256").update(text).digest("hex");

  it("preserves the original instructions and full static prefixes byte-for-byte", () => {
    // Captured from 16051748's actual builders, not generated by the migrated implementation.
    expect(hash(WORKING_MODE_TEXT)).toBe("73413a99baffdba62f0eaf804a5b5741c4bd2d678d84c900eb7ed6ee16991ff9");
    expect(hash(powerProfile(makeScene({ name: "写作场景" })).instructions))
      .toBe("8935c7cde83a6146af927a0e999d47627bd5c5f71c5896cecfc08a90de288995");
    for (const [profile, tools, segments, expected] of [
      [mainProfile(), [stubTool("Task"), entry()], undefined, "0d1fe387977259f5ffb211afc8370b8f3b96bb301414f34a8cf502cf5d8211ae"],
      [powerProfile({ ...makeScene({ name: "写作场景" }), hasWorkspace: true }), [stubTool("Task"), createWorkmodeExitTool()], undefined, "dc0d0708fec197a6c0202d9733c8fb24eca75a28290ec64888c073b499a3df7b"],
      [subAgentProfile({ subAgentId: "abc123def" }), [stubTool("read")], SUB_AGENT_SEGMENTS, "dceebe7a79d9978b694121793d7bc8743ffed24211c96b520b2bc6fd22083718"],
    ] as const) {
      const prefix = buildSystemPrompt({ profile, tools: [...tools], segments, cwd: "/test/project", skillIndex: "## Available Skills\n- reference" }).split(CACHE_BOUNDARY)[0]!;
      expect(hash(prefix)).toBe(expected);
    }
  });

  it("keeps scene choice, confirmation, workspace and turn-boundary decisions", () => {
    const prompt = buildSystemPrompt({ tools: [entry()], cwd: "/test/project" });
    expect(prompt).toContain(WORKING_MODE_TEXT);
    for (const content of ["workscene_list", "set_workdir", "clear_workdir", "optional device workspace", "ask the user before switching", "with confirmation", "finish the current turn normally", "Never request or transmit a remote filesystem path"]) {
      expect(prompt).toContain(content);
    }
    expect(prompt).not.toContain("workscene_memory_query");
  });

  it("follows the actual tool contribution, not a magic tool name", () => {
    const build = (tools: ToolDefinition[]) => buildSystemPrompt({ tools, cwd: "/test/project" });
    expect(build([stubTool("workmode_enter")])).not.toContain(WORKING_MODE_TEXT);
    expect(build([{ ...entry(), name: "renamed-entry" }])).toContain(WORKING_MODE_TEXT);
    expect(build([createWorkmodeExitTool()])).not.toContain(WORKING_MODE_TEXT);
    expect(build([])).not.toContain(WORKING_MODE_TEXT);
  });

  it("removes guidance when a job filters its contributing tool", () => {
    const select = (tools?: string[]) => selectJobRuntimeTools({
      instruction: { ...(tools ? { tools } : {}) } as never,
      baseProfile: mainProfile(), extraTools: [entry()], executionMcpServers: [],
      implementation: Object.freeze({ create: () => { throw new Error("not used"); } }),
    });
    const build = (selection: ReturnType<typeof select>) => buildSystemPrompt({
      profile: selection.profile, tools: [...selection.runtimeTools.extraTools], cwd: "/test/project",
    });
    expect(build(select())).toContain(WORKING_MODE_TEXT);
    expect(build(select(["workmode_enter"]))).toContain(WORKING_MODE_TEXT);
    expect(build(select(["read"]))).not.toContain(WORKING_MODE_TEXT);
  });
});
