import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/events/index.ts",
    "src/types/index.ts",
    "src/loop/index.ts",
    "src/resilience/index.ts",
    "src/context/index.ts",
    "src/transcript/index.ts",
    "src/conversation/index.ts",
    "src/conversation/application.ts",
    "src/advancement/application.ts",
    "src/workscene/application.ts",
    "src/rubrics/index.ts",
    "src/skills/catalog-application.ts",
    "src/product-api/catalog.ts",
    "src/trust-administration/application.ts",
    "src/advancement/index.ts",
    "src/resources/index.ts",
    "src/security/index.ts",
    "src/confirmation/index.ts",
    "src/identity/index.ts",
    "src/scheduler/index.ts",
    "src/scheduler/application.ts",
    "src/orchestration/index.ts",
    "src/contracts/index.ts",
    "src/protocol/index.ts",
    "src/persistence/index.ts",
    "src/authority/index.ts",
    "src/delivery/index.ts",
    "src/delivery/application.ts",
    "src/delivery/channel-effect.ts",
    "src/device-administration/application.ts",
    "src/device-administration/correctness.ts",
    "src/backup-recovery/application.ts",
    "src/environment/index.ts",
    "src/environment/workspace-administration.ts",
    "src/environment/workspace-probe-persistence.ts",
    "src/test-support/s7-durable.ts",
    "src/test-support/s7-durable-harness.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "node24",
});
