import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/events/index.ts",
    "src/types/index.ts",
    "src/loop/index.ts",
    "src/resilience/index.ts",
    "src/context/index.ts",
    "src/transcript/index.ts",
    "src/conversation/index.ts",
    "src/rubrics/index.ts",
    "src/skills/catalog-application.ts",
    "src/product-api/catalog.ts",
    "src/advancement/index.ts",
    "src/resources/index.ts",
    "src/security/index.ts",
    "src/confirmation/index.ts",
    "src/identity/index.ts",
    "src/scheduler/index.ts",
    "src/orchestration/index.ts",
    "src/contracts/index.ts",
    "src/protocol/index.ts",
    "src/persistence/index.ts",
    "src/authority/index.ts",
    "src/delivery/index.ts",
    "src/environment/index.ts",
    "src/test-support/s7-durable.ts",
    "src/test-support/s7-durable-harness.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "node24",
});
