import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/blind-relay.ts",
    "src/blind-rendezvous.ts",
    "src/bootstrap.ts",
    "src/index.ts",
    "src/canonical.ts",
    "src/checkpoint.ts",
    "src/bootstrap-authority.ts",
    "src/device-identity.ts",
    "src/device-key-store.ts",
    "src/device-readiness.ts",
    "src/credential-exposure.ts",
    "src/errors.ts",
    "src/handshake.ts",
    "src/outbound-tunnel.ts",
    "src/pairing-public.ts",
    "src/replay-window.ts",
    "src/request-channel.ts",
    "src/service-registry.ts",
    "src/recovery-root.ts",
    "src/trust-chain.ts",
    "src/transport.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "node22",
});
